Repository checkmarx-ltd/VSTS-Plugin, pull requests merged in 2021-09, with the labels that each got.

#22 Vsts engine config support
  CxScan/CxScanV20/services/configReader.ts
  CxScan/CxScanV20/task.json
Labels: size/S

#21 SCA Service Connection
  CxScan/CxScanV20/services/configReader.ts
  CxScan/CxScanV20/task.json
  vss-extension-dev.json
Labels: size/M

#24 Added teams and preset textboxes in Service Connection
  CxScan/CxScanV20/services/configReader.ts
  CxScan/CxScanV20/task.json
  vss-extension-dev.json
  vss-extension.json
Labels: size/L

#25 Changes for Incremental Scan
  CxScan/CxScanV20/services/configReader.ts
  CxScan/CxScanV20/task.json
Labels: size/M

#23 Post scan act id avoid dup scan support
  CxScan/CxScanV20/services/configReader.ts
  CxScan/CxScanV20/task.json
Labels: size/M
