Repository checkmarx-ltd/VSTS-Plugin, pull requests merged in 2022-02, with the labels that each got.

#33 Project custom fields
  CxScan/CxScanV20/services/configReader.ts
  CxScan/CxScanV20/task.json
Labels: size/S

#34 Pdf generation
  CxScan/CxScanV20/services/configReader.ts
  CxScan/CxScanV20/services/taskRunner.ts
  CxScan/CxScanV20/task.json
  Reports/cxreport.html
  Reports/scripts/cxTabReport.js
Labels: size/M

#35 Override project settings
  CxScan/CxScanV20/services/configReader.ts
  CxScan/CxScanV20/task.json
Labels: size/S

#36 Node version upgrade
  CxScan/CxScanV20/package.json
  CxScan/CxScanV20/task.json
Labels: size/XS

#37 proxy sca support
  CxScan/CxScanV20/services/configReader.ts
  CxScan/CxScanV20/task.json
Labels: size/L

#38 Issue fixes feb
  CxScan/CxScanV20/package.json
  CxScan/CxScanV20/services/configReader.ts
  CxScan/CxScanV20/task.json
  Reports/scripts/cxTabReport.js
  vss-extension-dev.json
Labels: size/S
